-- K.I.D. Mining Co. · Ejecuta este archivo completo en Supabase > SQL Editor.
create extension if not exists pgcrypto;

create type public.user_role as enum ('customer', 'worker', 'admin');
create type public.application_status as enum ('pending', 'approved', 'rejected');
create type public.order_status as enum ('pending', 'preparing', 'ready', 'completed', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  phone text not null default '',
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null check (price >= 0),
  category text not null,
  image_url text not null default 'assets/logo.png',
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null,
  phone text not null check (phone ~ '^[0-9]{5,15}$'),
  notes text not null default '',
  total numeric(12,2) not null check (total >= 0),
  status public.order_status not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create table public.job_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  applicant_name text not null,
  message text not null default '',
  status public.application_status not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, phone)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('worker', 'admin')
  );
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_notes text,
  p_items jsonb
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_order_id uuid;
  v_total numeric(12,2);
  v_requested integer;
  v_valid integer;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión'; end if;
  if trim(p_customer_name) = '' then raise exception 'Falta el nombre'; end if;
  if p_phone !~ '^[0-9]{5,15}$' then raise exception 'Teléfono no válido'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío';
  end if;

  select count(*) into v_requested from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer);
  select count(*), coalesce(sum(p.price * x.quantity), 0)
    into v_valid, v_total
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer)
  join public.products p on p.id = x.product_id and p.active
  where x.quantity > 0;

  if v_valid <> v_requested then raise exception 'Hay productos o cantidades no válidos'; end if;

  insert into public.orders (user_id, customer_name, phone, notes, total)
  values (auth.uid(), trim(p_customer_name), p_phone, coalesce(p_notes, ''), v_total)
  returning id into v_order_id;

  insert into public.order_items (order_id, product_id, product_name, unit_price, quantity)
  select v_order_id, p.id, p.name, p.price, x.quantity
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer)
  join public.products p on p.id = x.product_id and p.active;

  return v_order_id;
end;
$$;

create or replace function public.review_application(p_application_id uuid, p_decision public.application_status)
returns void language plpgsql security definer set search_path = public as $$
declare v_user_id uuid;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  update public.job_applications
  set status = p_decision, reviewed_at = case when p_decision = 'pending' then null else now() end
  where id = p_application_id returning user_id into v_user_id;
  if v_user_id is null then raise exception 'Solicitud no encontrada'; end if;
  if p_decision = 'approved' then
    update public.profiles set role = 'worker' where id = v_user_id and role = 'customer';
  elsif p_decision = 'rejected' then
    update public.profiles set role = 'customer' where id = v_user_id and role <> 'admin';
  end if;
end;
$$;

revoke all on function public.place_order(text,text,text,jsonb) from public;
grant execute on function public.place_order(text,text,text,jsonb) to authenticated;
revoke all on function public.review_application(uuid,public.application_status) from public;
grant execute on function public.review_application(uuid,public.application_status) to authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.job_applications enable row level security;

create policy "profiles_read_own_or_admin" on public.profiles
for select using (id = auth.uid() or public.is_admin());

create policy "profiles_admin_update" on public.profiles
for update using (public.is_admin()) with check (public.is_admin());

create policy "products_public_read" on public.products
for select using (active or public.is_staff());

create policy "products_admin_insert" on public.products
for insert with check (public.is_admin());

create policy "products_admin_update" on public.products
for update using (public.is_admin()) with check (public.is_admin());

create policy "products_admin_delete" on public.products
for delete using (public.is_admin());

create policy "orders_insert_own" on public.orders
for insert to authenticated with check (user_id = auth.uid());

create policy "orders_read_own_or_staff" on public.orders
for select to authenticated using (user_id = auth.uid() or public.is_staff());

create policy "orders_staff_update" on public.orders
for update to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "orders_staff_delete" on public.orders
for delete to authenticated using (public.is_staff());

create policy "items_insert_own_order" on public.order_items
for insert to authenticated with check (
  exists (select 1 from public.orders where id = order_id and user_id = auth.uid())
);

create policy "items_read_own_or_staff" on public.order_items
for select to authenticated using (
  public.is_staff() or exists (
    select 1 from public.orders where id = order_id and user_id = auth.uid()
  )
);

create policy "applications_insert_own" on public.job_applications
for insert to authenticated with check (user_id = auth.uid());

create policy "applications_read_own_or_admin" on public.job_applications
for select to authenticated using (user_id = auth.uid() or public.is_admin());

create policy "applications_admin_update" on public.job_applications
for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Productos iniciales. Puedes cambiarlos después desde el panel de administrador.
insert into public.products (name, price, category, image_url, description) values
('Hierro', 85, 'Metal industrial', 'assets/logo.png', 'Resistente, versátil y preparado para cualquier proyecto.'),
('Cobre', 120, 'Metal conductor', 'assets/logo.png', 'Perfecto para cableado, componentes y encargos especiales.'),
('Carbón', 65, 'Combustible mineral', 'assets/logo.png', 'Negro, fiable y disponible en grandes cantidades.'),
('Oro', 480, 'Metal precioso', 'assets/logo.png', 'Brilla, pesa y siempre conserva su valor.'),
('Plata', 310, 'Metal precioso', 'assets/logo.png', 'Elegante, limpia y seleccionada a mano.'),
('Diamante', 950, 'Gema premium', 'assets/logo.png', 'Difícil de encontrar e imposible de ignorar.');

-- Después de registrarte con tu cuenta de administrador, ejecuta SOLO esta línea
-- cambiando el correo. Así no existe ninguna contraseña de administrador en GitHub:
-- update public.profiles set role = 'admin' where email = 'tu-correo@ejemplo.com';
