-- K.I.D. Mining Co. · Instalación inicial de Supabase.
-- Ejecuta el archivo completo una sola vez en un proyecto vacío.

create extension if not exists pgcrypto;
create extension if not exists citext;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create type public.user_role as enum ('customer', 'worker', 'boss', 'admin');
create type public.application_status as enum ('pending', 'approved', 'rejected');
create type public.order_status as enum ('pending', 'preparing', 'ready', 'completed', 'cancelled');
create type public.inquiry_status as enum ('new', 'resolved');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique check (username::text ~ '^[a-z0-9._-]{3,24}$'),
  full_name text not null check (char_length(trim(full_name)) between 2 and 80),
  phone text not null check (phone ~ '^[0-9]{5,15}$'),
  role public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null check (price >= 0),
  category text not null,
  image_url text not null default 'assets/logo.png',
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete restrict,
  customer_name text not null,
  phone text not null check (phone ~ '^[0-9]{5,15}$'),
  notes text not null default '',
  total numeric(12,2) not null check (total >= 0),
  status public.order_status not null default 'pending',
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create table public.job_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  applicant_name text not null,
  message text not null default '',
  status public.application_status not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 2 and 80),
  phone text not null check (phone ~ '^[0-9]{5,15}$'),
  message text not null check (char_length(trim(message)) between 5 and 2000),
  status public.inquiry_status not null default 'new',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index profiles_role_idx on public.profiles (role);
create index orders_user_created_idx on public.orders (user_id, created_at desc);
create index orders_status_created_idx on public.orders (status, created_at desc);
create index order_items_order_idx on public.order_items (order_id);
create index order_items_product_idx on public.order_items (product_id);
create index applications_status_created_idx on public.job_applications (status, created_at desc);
create index inquiries_status_created_idx on public.inquiries (status, created_at desc);

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, full_name, phone)
  values (
    new.id,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'phone'
  );
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('worker', 'boss', 'admin')
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('boss', 'admin')
  );
$$;

revoke all on function private.is_staff() from public;
revoke all on function private.is_admin() from public;
grant execute on function private.is_staff() to anon, authenticated;
grant execute on function private.is_admin() to authenticated;

create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_notes text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_total numeric(12,2);
  v_requested integer;
  v_valid integer;
begin
  if trim(p_customer_name) = '' then raise exception 'Falta el nombre'; end if;
  if p_phone !~ '^[0-9]{5,15}$' then raise exception 'Teléfono no válido'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío';
  end if;

  select count(*) into v_requested
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer);

  select count(*), coalesce(sum(p.price * x.quantity), 0)
  into v_valid, v_total
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer)
  join public.products p on p.id = x.product_id and p.active
  where x.quantity > 0;

  if v_valid <> v_requested then raise exception 'Hay productos o cantidades no válidos'; end if;

  insert into public.orders (user_id, customer_name, phone, notes, total)
  values ((select auth.uid()), trim(p_customer_name), p_phone, coalesce(p_notes, ''), v_total)
  returning id into v_order_id;

  insert into public.order_items (order_id, product_id, product_name, unit_price, quantity)
  select v_order_id, p.id, p.name, p.price, x.quantity
  from jsonb_to_recordset(p_items) as x(product_id bigint, quantity integer)
  join public.products p on p.id = x.product_id and p.active;

  return v_order_id;
end;
$$;

create or replace function public.review_application(
  p_application_id uuid,
  p_decision public.application_status,
  p_role public.user_role default 'worker'
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare v_user_id uuid;
begin
  if not private.is_admin() then raise exception 'Acceso denegado'; end if;
  if p_decision = 'approved' and p_role not in ('worker', 'boss') then
    raise exception 'Rol de equipo no válido';
  end if;

  update public.job_applications
  set status = p_decision,
      reviewed_at = case when p_decision = 'pending' then null else now() end
  where id = p_application_id
  returning user_id into v_user_id;

  if v_user_id is null then raise exception 'Solicitud no encontrada'; end if;

  if p_decision = 'approved' then
    update public.profiles set role = p_role
    where id = v_user_id and role = 'customer';
  elsif p_decision = 'rejected' then
    update public.profiles set role = 'customer'
    where id = v_user_id and role not in ('boss', 'admin');
  end if;
end;
$$;

revoke all on function public.place_order(text,text,text,jsonb) from public;
grant execute on function public.place_order(text,text,text,jsonb) to anon, authenticated;
revoke all on function public.review_application(uuid,public.application_status,public.user_role) from public, anon;
grant execute on function public.review_application(uuid,public.application_status,public.user_role) to authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.job_applications enable row level security;
alter table public.inquiries enable row level security;

create policy "profiles_read_own_or_admin" on public.profiles
for select to authenticated
using (id = (select auth.uid()) or private.is_admin());

create policy "profiles_admin_update" on public.profiles
for update to authenticated
using (private.is_admin()) with check (private.is_admin());

create policy "products_public_read" on public.products
for select to anon, authenticated
using (active or private.is_staff());

create policy "products_admin_insert" on public.products
for insert to authenticated with check (private.is_admin());

create policy "products_admin_update" on public.products
for update to authenticated
using (private.is_admin()) with check (private.is_admin());

create policy "products_admin_delete" on public.products
for delete to authenticated using (private.is_admin());

create policy "orders_read_own_or_staff" on public.orders
for select to authenticated
using (user_id = (select auth.uid()) or private.is_staff());

create policy "orders_staff_update" on public.orders
for update to authenticated
using (private.is_staff()) with check (private.is_staff());

create policy "orders_staff_delete" on public.orders
for delete to authenticated using (private.is_staff());

create policy "items_read_own_or_staff" on public.order_items
for select to authenticated
using (
  private.is_staff() or exists (
    select 1 from public.orders
    where id = order_id and user_id = (select auth.uid())
  )
);

create policy "applications_insert_own" on public.job_applications
for insert to authenticated
with check (user_id = (select auth.uid()));

create policy "applications_read_own_or_admin" on public.job_applications
for select to authenticated
using (user_id = (select auth.uid()) or private.is_admin());

create policy "applications_admin_update" on public.job_applications
for update to authenticated
using (private.is_admin()) with check (private.is_admin());

create policy "inquiries_public_insert" on public.inquiries
for insert to anon, authenticated
with check (
  status = 'new'
  and phone ~ '^[0-9]{5,15}$'
  and char_length(trim(name)) between 2 and 80
  and char_length(trim(message)) between 5 and 2000
);

create policy "inquiries_admin_read" on public.inquiries
for select to authenticated using (private.is_admin());

create policy "inquiries_admin_update" on public.inquiries
for update to authenticated
using (private.is_admin()) with check (private.is_admin());

create policy "inquiries_admin_delete" on public.inquiries
for delete to authenticated using (private.is_admin());

grant select on public.products to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant insert, update, delete on public.products to authenticated;
grant select, update, delete on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant select, insert, update on public.job_applications to authenticated;
grant insert on public.inquiries to anon, authenticated;
grant select, update, delete on public.inquiries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.products (name, price, category, image_url, description) values
('Hierro', 85, 'Metal industrial', 'assets/logo.png', 'Resistente, versátil y preparado para cualquier proyecto.'),
('Cobre', 120, 'Metal conductor', 'assets/logo.png', 'Perfecto para cableado, componentes y encargos especiales.'),
('Carbón', 65, 'Combustible mineral', 'assets/logo.png', 'Negro, fiable y disponible en grandes cantidades.'),
('Oro', 480, 'Metal precioso', 'assets/logo.png', 'Brilla, pesa y siempre conserva su valor.'),
('Plata', 310, 'Metal precioso', 'assets/logo.png', 'Elegante, limpia y seleccionada a mano.'),
('Diamante', 950, 'Gema premium', 'assets/logo.png', 'Difícil de encontrar e imposible de ignorar.');

-- Después de crear tu cuenta, convierte el primer usuario en administrador:
-- update public.profiles set role = 'admin' where username = 'tu_usuario';
