-- Permite borrar tickets de gastos de la lista sin perder su efecto contable.
-- expenses guarda las tarjetas visibles; expense_ledger guarda el historial
-- permanente que sigue restando aunque la tarjeta se elimine.

drop function if exists public.hide_expense(uuid);

alter table public.expenses
drop column if exists hidden_at,
drop column if exists hidden_by;

create table if not exists public.expense_ledger (
  id bigint generated by default as identity primary key,
  expense_id uuid not null unique,
  amount numeric(12,2) not null check (amount > 0),
  concept text not null,
  created_by_name text not null,
  spent_at timestamptz not null,
  cancelled_at timestamptz
);

create index if not exists expense_ledger_spent_idx on public.expense_ledger (spent_at desc);
create index if not exists expense_ledger_active_idx on public.expense_ledger (spent_at desc)
where cancelled_at is null;

alter table public.expense_ledger enable row level security;

drop policy if exists "expense_ledger_management_read" on public.expense_ledger;
create policy "expense_ledger_management_read" on public.expense_ledger
for select to authenticated
using (private.is_admin());

grant select on public.expense_ledger to authenticated;

insert into public.expense_ledger (
  expense_id,
  amount,
  concept,
  created_by_name,
  spent_at,
  cancelled_at
)
select
  id,
  amount,
  concept,
  created_by_name,
  created_at,
  cancelled_at
from public.expenses
on conflict (expense_id) do update
set amount = excluded.amount,
    concept = excluded.concept,
    created_by_name = excluded.created_by_name,
    spent_at = excluded.spent_at,
    cancelled_at = excluded.cancelled_at;

create or replace function public.create_expense(
  p_amount numeric,
  p_concept text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expense_id uuid;
  v_name text;
begin
  if not private.is_admin() then
    raise exception 'Acceso denegado';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'El importe debe ser mayor que cero';
  end if;

  if char_length(trim(coalesce(p_concept, ''))) not between 2 and 500 then
    raise exception 'Escribe un concepto válido';
  end if;

  select full_name into v_name
  from public.profiles
  where id = (select auth.uid());

  if v_name is null then
    raise exception 'Perfil no encontrado';
  end if;

  insert into public.expenses (
    amount,
    concept,
    created_by,
    created_by_name
  )
  values (
    round(p_amount, 2),
    trim(p_concept),
    (select auth.uid()),
    v_name
  )
  returning id into v_expense_id;

  insert into public.expense_ledger (
    expense_id,
    amount,
    concept,
    created_by_name,
    spent_at
  )
  values (
    v_expense_id,
    round(p_amount, 2),
    trim(p_concept),
    v_name,
    now()
  );

  return v_expense_id;
end;
$$;

create or replace function public.cancel_expense(p_expense_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'Acceso denegado';
  end if;

  update public.expenses
  set cancelled_at = now(),
      cancelled_by = (select auth.uid())
  where id = p_expense_id
    and cancelled_at is null;

  if not found then
    raise exception 'Ticket no encontrado o ya cancelado';
  end if;

  update public.expense_ledger
  set cancelled_at = now()
  where expense_id = p_expense_id
    and cancelled_at is null;
end;
$$;

create or replace function public.delete_expense(p_expense_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'Acceso denegado';
  end if;

  delete from public.expenses
  where id = p_expense_id;

  if not found then
    raise exception 'Ticket no encontrado';
  end if;
end;
$$;

revoke all on function public.delete_expense(uuid) from public, anon;
revoke all on function public.create_expense(numeric,text) from public, anon;
revoke all on function public.cancel_expense(uuid) from public, anon;
grant execute on function public.delete_expense(uuid) to authenticated;
grant execute on function public.create_expense(numeric,text) to authenticated;
grant execute on function public.cancel_expense(uuid) to authenticated;
