-- Historial permanente de ingresos y tickets de gastos.
-- El historial no tiene una clave foránea hacia orders a propósito: así el
-- ingreso sobrevive cuando el pedido se elimina para liberar espacio.

create table public.revenue_ledger (
  id bigint generated by default as identity primary key,
  order_id uuid not null unique,
  customer_name text not null,
  amount numeric(12,2) not null check (amount >= 0),
  completed_at timestamptz not null default now()
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  amount numeric(12,2) not null check (amount > 0),
  concept text not null check (char_length(trim(concept)) between 2 and 500),
  created_by uuid references public.profiles(id) on delete set null,
  created_by_name text not null,
  created_at timestamptz not null default now(),
  cancelled_at timestamptz,
  cancelled_by uuid references public.profiles(id) on delete set null
);

create index expenses_created_idx on public.expenses (created_at desc);
create index expenses_active_idx on public.expenses (created_at desc)
where cancelled_at is null;
create index revenue_completed_idx on public.revenue_ledger (completed_at desc);

alter table public.revenue_ledger enable row level security;
alter table public.expenses enable row level security;

create policy "revenue_management_read" on public.revenue_ledger
for select to authenticated
using (private.is_admin());

create policy "expenses_management_read" on public.expenses
for select to authenticated
using (private.is_admin());

grant select on public.revenue_ledger to authenticated;
grant select on public.expenses to authenticated;

create or replace function private.record_completed_order_revenue()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'completed'
     and (tg_op = 'INSERT' or old.status is distinct from 'completed') then
    insert into public.revenue_ledger (
      order_id,
      customer_name,
      amount,
      completed_at
    )
    values (
      new.id,
      new.customer_name,
      new.total,
      now()
    )
    on conflict (order_id) do nothing;
  end if;

  return new;
end;
$$;

revoke all on function private.record_completed_order_revenue() from public, anon, authenticated;

create trigger record_completed_order_revenue
after insert or update of status on public.orders
for each row execute function private.record_completed_order_revenue();

-- Conserva en el historial los pedidos que ya estuvieran completados cuando
-- se ejecute esta migración.
insert into public.revenue_ledger (order_id, customer_name, amount, completed_at)
select id, customer_name, total, created_at
from public.orders
where status = 'completed'
on conflict (order_id) do nothing;

create or replace function public.create_expense(
  p_amount numeric,
  p_concept text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_expense_id uuid;
  v_name text;
begin
  if not private.is_admin() then
    raise exception 'Acceso denegado';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'El importe debe ser mayor que cero';
  end if;

  if char_length(trim(coalesce(p_concept, ''))) not between 2 and 500 then
    raise exception 'Escribe un concepto válido';
  end if;

  select full_name into v_name
  from public.profiles
  where id = (select auth.uid());

  if v_name is null then
    raise exception 'Perfil no encontrado';
  end if;

  insert into public.expenses (
    amount,
    concept,
    created_by,
    created_by_name
  )
  values (
    round(p_amount, 2),
    trim(p_concept),
    (select auth.uid()),
    v_name
  )
  returning id into v_expense_id;

  return v_expense_id;
end;
$$;

create or replace function public.cancel_expense(p_expense_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception 'Acceso denegado';
  end if;

  update public.expenses
  set cancelled_at = now(),
      cancelled_by = (select auth.uid())
  where id = p_expense_id
    and cancelled_at is null;

  if not found then
    raise exception 'Ticket no encontrado o ya cancelado';
  end if;
end;
$$;

revoke all on function public.create_expense(numeric,text) from public, anon;
revoke all on function public.cancel_expense(uuid) from public, anon;
grant execute on function public.create_expense(numeric,text) to authenticated;
grant execute on function public.cancel_expense(uuid) to authenticated;
